version: '3'

services:
  flask:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    env_file:
      - ./config/.env
    stdin_open: true  # For PDB debugging
    tty: true         # For PDB debugging
    restart: on-failure
    depends_on:
      - mongodb
    networks:
      - backend
  
  mongodb:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - 27017:27017
    command: mongod
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
